version: '3'

services:

  db:
    build: ./postgres
    container_name: database
    hostname: db
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/

  backend_django:
    build:
      context: .
    working_dir: /app/backend/
    container_name: dj_react
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
