version: '3'

services:

  db:
    build: ./postgres
    container_name: database
    hostname: db
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/

  backend_django:
    build:
      context: ./backend
    working_dir: /app/backend/
    container_name: backend_django
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend_react:
    build:
      context: ./frontend
    working_dir: /app/frontend/
    container_name: frontend_django
    volumes:
      - .:/app/
    ports:
      - "3000:3000"
