version: '3'

services:
  backend_django:
    build:
      context: .
    working_dir: /app/backend/
    container_name: dj_react
    command: python3 manage.py runserver 0.0.0.0:8000
    tty: true
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
