# Generated by Django 2.2.6 on 2019-11-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='decription',
            new_name='description',
        ),
    ]
